name: sc_foundation_evals
channels:
  - pytorch
  - nvidia/label/cuda-11.7.0
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python==3.10
  - r-base
  - pip
  - cuda==11.7.0
  - ninja
  - rpy2
  - packaging
  - gxx==11.4
  - git-lfs
  - pip:
    - --index-url https://download.pytorch.org/whl/cu117
    - torch==1.13
    - torchvision
    - torchaudio
    - wandb
    - colorlog 
    - PyComplexHeatmap
    - scib[kBET,rpy2]
